import { Buffer } from 'buffer';
import express from 'express';
import { Job } from '../models/Job.js';
import { requireAuth, AuthRequest } from '../middleware/auth.js';
import { GoogleGenAI } from "@google/genai";
import PDFDocument from 'pdfkit';

const router = express.Router();

router.use(requireAuth);

// Get all jobs for the current user
router.get('/', async (req: AuthRequest, res) => {
  try {
    const jobs = await (Job as any).find({ userId: req.user._id }).sort({ createdAt: -1 });
    res.json(jobs);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Create a new job manually
router.post('/', async (req: AuthRequest, res) => {
  try {
    const jobData = { ...req.body };
    if (!jobData.title && jobData.role) {
      jobData.title = jobData.role;
    }
    if (jobData.hrEmail || jobData.managerName) {
      jobData.hrContact = {
        name: jobData.managerName || '',
        email: jobData.hrEmail || '',
        linkedin: ''
      };
    }
    const job = new (Job as any)({
      ...jobData,
      userId: req.user._id
    });
    await job.save();
    res.status(201).json(job);

    // Background trigger for new manual jobs
    if (!jobData.outreachAttempted && jobData.profile && jobData.gmailToken && process.env.GEMINI_API_KEY) {
      (async () => {
        try {
          const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
          const response = await ai.models.generateContent({
            model: "gemini-2.5-pro",
            contents: [`
              You are an AI assistant helping a candidate find HR contact info and draft outreach messages.
              Job Context: Job Title: ${jobData.title}, Company: ${jobData.company}
              Candidate Profile: ${JSON.stringify(jobData.profile)}
              
              Respond with a JSON object containing:
              1. "hrEmail": string
              2. "hrPhone": string or null
              3. "emailDraft": string
              4. "whatsappDraft": string
              5. "atsResume": string (a tailored text-based ATS friendly resume based on the profile)
            `],
            config: {
              responseMimeType: "application/json",
            }
          });
          const text = response.text;
          if (text) {
             const aiData = JSON.parse(text);
             const hrEmail = aiData?.hrEmail || `hr@${jobData.company.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`;
             const atsResume = aiData?.atsResume || "No resume generated.";
             const hrPhone = aiData?.hrPhone;
             
             // generate PDF
             const doc = new PDFDocument();
             const buffers: Buffer[] = [];
             doc.on('data', buffers.push.bind(buffers));
             doc.on('end', async () => {
               const pdfBuffer = Buffer.concat(buffers);
               const pdfBase64 = pdfBuffer.toString('base64');
               const pdfName = `Resume_${jobData.profile.name?.replace(/ /g, '_') || 'Candidate'}.pdf`;
               
               
               if (hrPhone && hrPhone !== 'null') {
                 // For WhatsApp, we simulate sending by logging and updating the job
                 console.log('Would send WhatsApp draft to', hrPhone, 'for', jobData.company);
                 job.outreachAttempted = true;
                 job.outreachType = 'whatsapp';
                 await job.save();
                 
                 try {
                     const projectId = "hopeful-mesh-2f4nj";
                     await fetch(`https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/users/${req.user._id}/applications/${jobData.id}?updateMask.fieldPaths=outreachAttempted&updateMask.fieldPaths=outreachType`, {
                       method: 'PATCH',
                       headers: {
                         'Authorization': `Bearer ${jobData.gmailToken}`,
                         'Content-Type': 'application/json'
                       },
                       body: JSON.stringify({
                         fields: {
                           outreachAttempted: { booleanValue: true },
                           outreachType: { stringValue: 'whatsapp' }
                         }
                       })
                     });
                 } catch(e) {}
               } else {

                 const emailContent = `${aiData?.emailDraft?.replace(/\n/g, '<br>') || 'Hi, I am interested in this role.'}<br><br><strong>ATS-Friendly Resume:</strong><br><pre>${atsResume}</pre><br><br>---<br>This email is system generated and the system is generated by Aakash Saini.`;
                 
                 // use local endpoint or directly hit gmail api
                 const boundary = 'foo_bar_baz';
                 const emailLines = [
                   `To: ${hrEmail}`,
                   `Subject: Application: ${jobData.title} - ${jobData.profile.name}`,
                   `Content-Type: multipart/mixed; boundary="${boundary}"`,
                   '',
                   `--${boundary}`,
                   'Content-Type: text/html; charset=utf-8',
                   '',
                   emailContent,
                   '',
                   `--${boundary}`,
                   `Content-Type: application/pdf; name="${pdfName}"`,
                   `Content-Disposition: attachment; filename="${pdfName}"`,
                   'Content-Transfer-Encoding: base64',
                   '',
                   pdfBase64,
                   `--${boundary}--`,
                   ''
                 ];
                 const emailString = emailLines.join('\r\n');
                 const base64EncodedEmail = Buffer.from(emailString)
                    .toString('base64')
                    .replace(/\+/g, '-')
                    .replace(/\//g, '_')
                    .replace(/=+$/, '');
                    
                 const gmailRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
                    method: 'POST',
                    headers: {
                      'Authorization': `Bearer ${jobData.gmailToken}`,
                      'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ raw: base64EncodedEmail }),
                 });
                 
                 if (gmailRes.ok) {
                   job.outreachAttempted = true;
                   job.outreachType = 'email';
                   await job.save();
                   
                   // Update Firestore using REST API
                   try {
                     const projectId = "hopeful-mesh-2f4nj";
                     await fetch(`https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/users/${req.user._id}/applications/${jobData.id}?updateMask.fieldPaths=outreachAttempted&updateMask.fieldPaths=outreachType`, {
                       method: 'PATCH',
                       headers: {
                         'Authorization': `Bearer ${jobData.gmailToken}`,
                         'Content-Type': 'application/json'
                       },
                       body: JSON.stringify({
                         fields: {
                           outreachAttempted: { booleanValue: true },
                           outreachType: { stringValue: 'email' }
                         }
                       })
                     });
                   } catch(e) { console.error('Failed to update firestore', e); }
                 }

               }
             });
             
             doc.fontSize(22).text(jobData.profile.name || "Candidate Name", 20, 30);
             doc.fontSize(12).text(jobData.profile.email || "email@example.com", 20, 40);
             doc.text("Professional Resume", 20, 50);
             doc.text(atsResume, 20, 60);
             doc.end();
          }
        } catch (e) {
          console.error('Background trigger failed:', e);
        }
      })();
    }
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Update a job status
router.patch('/:id/status', async (req: AuthRequest, res) => {
  try {
    const { status } = req.body;
    const job = await (Job as any).findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id },
      { status },
      { new: true }
    );
    if (!job) return res.status(404).json({ error: 'Job not found' });
    res.json(job);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
